#!/bin/sh

CLASSPATH="./libs/:./libs/js.jar:./libs/servlet-api-2.5-6.1.6.jar:./libs/jetty-util-6.1.6.jar:./libs/jetty-ajp-6.1.5.jar:./libs/jetty-6.1.6.jar:./libs/mysql-connector-java-3.0.17-ga-bin.jar:./libs/cometd-api-0.9.20071105.jar:./libs/cometd-bayeux-6.1.6.jar:./libs/bayeux-client-6.1.6.jar"

#java -classpath ${CLASSPATH} EmbeddedServerSideApp
#java -classpath ${CLASSPATH} org.mozilla.javascript.tools.shell.Main bootstrap.js
#java -classpath ${CLASSPATH} org.mozilla.javascript.tools.shell.Main test.js

# uncomment to set JAVA_HOME variable
JAVA_HOME=/opt/lampp/jdk1.5.0_10

if [ "$JAVA_HOME" ]; then
   JAVACMD="$JAVA_HOME/bin/java"
else
   JAVACMD=java
fi

# If JAVA_HOME is set, check if java command is executable
if [ $JAVA_HOME -a ! -x $JAVACMD ] ; then
   echo "Warning: JAVA_HOME variable may be set incorrectly:"
   echo "         No executable found at $JAVACMD"
fi

echo "Starting MooServer"


# Invoke the Java VM
$JAVACMD -classpath ${CLASSPATH} org.mozilla.javascript.tools.shell.Main rhimoo/server.js
