#!/bin/sh

CLASSPATH="./libs/:./libs/js.jar:./libs/servlet-api-2.5-6.1.6.jar:./libs/jetty-util-6.1.6.jar:./libs/jetty-ajp-6.1.5.jar:./libs/jetty-6.1.6.jar:./libs/mysql-connector-java-3.0.17-ga-bin.jar:./libs/cometd-api-0.9.20071105.jar:./libs/cometd-bayeux-6.1.6.jar:./libs/bayeux-client-6.1.6.jar:./libs/rhinoloader.jar"

java -classpath ${CLASSPATH} org.mozilla.javascript.tools.shell.Main test2.js

#java -classpath ${CLASSPATH} MooServer
